webapp/user/urls.py
from django.urls import path
from user.views import Usereditprofile, register, signin,signout,home,editprofile
# from django.conf.urls import url
from user import views


urlpatterns = [
    path('',home,name='register'),
    path('login/', signin,name='login'),
    path('Kaydol', register,name='register'),
    path('logout/',signout,name='logout'),
    path('profil/',editprofile,name='editprofile'),
    path('profil/duzenle/',views.Usereditprofile.as_view(),name='editprofileuser'),
    path(r'^password/$', views.change_password, name='change_password'),
]

webapp/webapp/urls.py
from django.conf.urls.static import static  #media dosyası yapmak için 
from django.conf import settings            #media dosyası yapmak için 
from django.contrib import admin
from django.urls import path,include

admin.site.site_title = 'Seismo'
admin.site.site_header = 'Seismo Administrator'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    # path('app/', include('app.urls')),
    path('kullanıcı/',include('user.urls')), 
    path('adminpanel/',include('adminpanel.urls')),
    path('yazarpanel/',include('writerpanel.urls')),
    # path('writer/',include('writerpanel.urls')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #media dosyası yapmak için settings de de ayarlar varfrom django.urls import include, path
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/writerpanel/urls.py
from django.urls import path
from writerpanel.views import *
from django.conf import settings
from django.conf.urls.static import static   
    
#writers
urlpatterns = [
path('',ListPosts.as_view(),name='my_writings'),
path('Haber_düzenle/<slug:slug>/',DetailPosts.as_view(),name='edit_news'),
path('Makale_düzenle/<slug:slug>/',DetailArticle.as_view(),name='edit_article'),
path('Haber_ekle/',AddPosts.as_view(),name='add_news'),
path('Makale_ekle/',AddArticle.as_view(),name='add_article'),
path('Haber_düzenle/<slug:slug>/delete/', DeletePostsView.as_view(),name='delete'),
path('Makale_düzenle/<slug:slug>/delete/', DeleteArticleView.as_view(),name='deletearticle'),
]
urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/website/models/makale.py
from django.db import models
from autoslug import AutoSlugField
from django.urls import reverse
from website.abstract_model import DateAbstractModel
from user.models import User


class MakalelerModel(DateAbstractModel):
    baslik = models.CharField(max_length=50)
    makale = models.FileField(upload_to='makale_pdf/',null=True)
    slug = AutoSlugField(populate_from = 'baslik', unique = True)#kaldır
    #çoktan çoğa db ilişkisi
    #models.CASCADE kullanıcı silinir ise yazılarını da siler
    #related name ler ise ilişkilendirme isimleri
    yazar = models.ForeignKey(User,on_delete=models.SET_NULL,related_name='makaleler',null=True) 

    class Meta:
        verbose_name = 'makale'
        verbose_name_plural = 'makaleler'

    def get_absolute_url(self):
            return reverse('article-details', kwargs={'slug': self.slug})

    def __str__(self) :
        return  self.baslik

webapp/website/models/yazi.py
from django.db import models
from autoslug import AutoSlugField
from django.urls import reverse
from ckeditor.fields import RichTextField
from website.abstract_model import DateAbstractModel
from user.models import User


class YazilarModel(DateAbstractModel):
    resim = models.ImageField(upload_to='yazi_resimler')
    baslik = models.CharField(max_length=50)
    icerik = RichTextField()
    slug = AutoSlugField(populate_from = 'baslik',unique = True)
    # kategoriler = models.ManyToManyField(KategoriModel, related_name='yazi') #çoktan çoğa db ilişkisi
    #models.CASCADE kullanıcı silinir ise yazılarını da siler
    #related name ler ise ilişkilendirme isimleri
    yazar= models.ForeignKey(User,on_delete=models.SET_NULL,related_name='yazilar',null=True) 

    def __str__(self):
         return self.yazar

    class Meta:
        verbose_name = 'yazi'
        verbose_name_plural = 'yazilar'

    def get_absolute_url(self):

            return reverse('news-details', kwargs={'slug': self.slug})

    def __str__(self) :
        return  self.baslik

webapp/writerpanel/models.py
from django.db import models

# Create your models here.

webapp/writerpanel/forms.py
from django.forms import ModelForm
from django import forms
from website.models.makale import MakalelerModel
from website.models.yazi import YazilarModel
import os

# class CreatePostsForm(forms.ModelForm):
#     class Meta:
#         model = YazilarModel
#         fields =['resim','baslik','icerik','yazar']


class UpdatePostsForm(ModelForm):
    class Meta:
        model=YazilarModel
        fields=['resim','baslik','icerik']


class UpdateArticlesForm(ModelForm):
    class Meta:
        model=MakalelerModel
        fields=['baslik','makale',]

        

    # image = forms.FileField()

    # def clean_image(self):
    #     uploaded_file = self.cleaned_data['image']
    #     try:
    #         # create an ImageField instance
    #         im = forms.ImageField()
    #         # now check if the file is a valid image
    #         im.to_python(uploaded_file)
    #     except forms.ValidationError:
    #         # file is not a valid image;
    #         # so check if it's a pdf
    #         name, ext = os.path.splitext(uploaded_file.name)
    #         if ext not in ['.pdf', '.PDF']:
    #             raise forms.ValidationError("Only images and PDF files allowed")
    #     return uploaded_file

webapp/writerpanel/views.py
from django.views.generic import ListView
from website.models.makale import MakalelerModel
from .forms import  UpdatePostsForm, UpdateArticlesForm
from website.models.yazi import YazilarModel
from django.views.generic.edit import UpdateView,CreateView,DeleteView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib import messages


User=get_user_model()


class AddPosts(PermissionRequiredMixin,LoginRequiredMixin,CreateView): #DÜZENLEMESİ GEREKEN FİELDS KISIMLARI VAR
    model = YazilarModel
    template_name = "writers/add-news.html"
    success_url = '/yazarpanel/'
    fields = ['resim','baslik','icerik',]
    permission_required = 'website.add_yazilarmodel'
        
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.yazar = self.request.user
        self.object.save()
        return super(AddPosts,self).form_valid(form)

    def handle_no_permission(self):
        # add custom message
        messages.error(self.request, 'You have no permission')
        return super(AddPosts, self).handle_no_permission()


class  ListPosts(PermissionRequiredMixin,LoginRequiredMixin,ListView):
    model = YazilarModel
    template_name = "writers/my-writings.html"
    permission_required = 'website.view_yazilarmodel'

    def get_context_data(self ,**kwargs):
        context = super(ListPosts, self).get_context_data(**kwargs)
        context['writers']=YazilarModel.objects.filter(yazar=self.request.user).order_by('-olusturulma_tarihi')
        context['articles'] = MakalelerModel.objects.all().filter(yazar=self.request.user).order_by('-olusturulma_tarihi')
        return context

    # def get_queryset(self):
    #     if self.kwargs.get('pk'):
    #         text_writer = YazilarModel.objects.filter(
    #             yazar=self.kwargs.get('pk')).values('yazar_id')

    #         return User.objects.filter(id__in=text_writer, roles=Role.WRITER)

    #     return User.objects.all()
    
    
#yazı haber 
class  DetailPosts(PermissionRequiredMixin,LoginRequiredMixin,UpdateView):
    model = YazilarModel
    template_name = "writers/edit-news.html"
    context_object_name = 'post'
    success_url = '/yazarpanel/'
    form_class = UpdatePostsForm
    permission_required = 'website.view_yazilarmodel'


class DeletePostsView(PermissionRequiredMixin,LoginRequiredMixin,DeleteView):
    model = YazilarModel
    success_url = '/yazarpanel/'   
    template_name = "writers/delete.html"
    permission_required = 'website.delete_yazilarmodel'


#makale

class AddArticle(PermissionRequiredMixin,LoginRequiredMixin,CreateView):#DÜZENLEMESİ GEREKEN FİELDS KISIMLARI VAR
    model = MakalelerModel
    template_name = "writers/add-article.html"
    success_url = '/yazarpanel/'
    fields =  ['baslik','makale',]
    permission_required = 'website.add_makalelermodel'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.yazar = self.request.user
        self.object.save()
        return super(AddArticle,self).form_valid(form)


class  DetailArticle(PermissionRequiredMixin,LoginRequiredMixin,UpdateView):
    model = MakalelerModel
    template_name = "writers/edit-article.html"
    context_object_name = 'article'
    success_url = '/yazarpanel/'
    form_class = UpdateArticlesForm
    permission_required = 'website.view_makalelermodel'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.makale=form.cleaned_data['makale']
        # self.object.makale = form.request.FILES['makale']
        self.object.save()
        return super(DetailArticle,self).form_valid(form)


class DeleteArticleView(PermissionRequiredMixin,LoginRequiredMixin,DeleteView):
    model = MakalelerModel
    success_url = '/yazarpanel/'   
    template_name = "writers/delete.html"  
    permission_required = 'website.delete_makalelermodel'
    

webapp/writerpanel/templates/writers/add-article.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Makale Ekle {% endblock %} 


{% block content %}
<form action="" enctype="multipart/form-data" method="post">
  {% csrf_token %}

<div class="container mt-2 ">
    <h1>Makale Ekle</h1>
    <div class="card">
      <div class="card-body">
        <div>
          <label class="required" for="id_baslik">Başlık:</label>
          <input class="form-control d-flex flex-row" name="baslik" id="baslik"type="text" placeholder="Başlık"> 
        </div>
        <p class="file-upload mt-2">
          Yüklenecek Makale:
          <input type="file" name="makale" accept="application/pdf" id="makale">
        </p>
      </div>
    </div>
</div>
  <div class="container mt-2 d-flex flex-row-reverse">
    {% comment %} <button type="button" class="btnkayit btn btn-success ">Kontrol Et</button> {% endcomment %}
    <button type="submit" class="btnkayit btn btn-success me-2" id="submit" name="submit" value="submit">Kaydet</button>
  </div>
</form>
  {% endblock  %}

webapp/writerpanel/templates/writers/add-news.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Haber Ekle {% endblock %} 


{% block content %}
{% comment %} {% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} {% endcomment %}
<form action="" enctype="multipart/form-data" method="POST">
  {% csrf_token %}
    <div class="container mt-2 ">
     <h1>Haber Ekle</h1>
     {{form.media}}
      <div class="card">
        <div class="card-body">
          <p class="file-upload">
            Resim:
            <input type="file" name="resim" accept="image/*" id="resim">
          </p>
          <div>
            <label class="required" for="id_baslik">Başlık:</label>
            <input class="form-control d-flex flex-row" name="baslik" id="baslik"type="text" placeholder="Başlık">  
          </div>
            <h2 class="mt-2"></h2>
            İçerik:
            <br>
            {{form.icerik}}
            {% comment %} {{form.yazar}} {% endcomment %}
        </div>
      </div> 

    </div>
    <div class="container mt-2 d-flex flex-row-reverse">
      {% comment %} <button type="button" class="btnkayit btn btn-success ">Kontrol Et</button> {% endcomment %}
      <button type="submit" class="btnkayit btn btn-success me-2" id="submit" name="submit" value="submit">Kaydet</button>
    </div>
  </form>


    {% endblock  %}

webapp/writerpanel/templates/writers/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Makale Ekle {% endblock %} 


{% block content %}

<div class="container mt-5 d-flex justify-content-center ">
    
<form method="post">{% csrf_token %}
    <div class="card">
        <div class="card-body">
            <p>Silinsin mi "{{ object }}"?</p>
        </div> 
    </div> 
    <div class="d-flex justify-content-end mt-2 ">
        <a type="" name="url" class="btnkayit btn btn-success me-2"  href="{% url 'my_writings' %}">Vazgeç</a>
        <input type="submit" class="btn btn-danger me-2"  value="Sil">
    </div> 
</form>
</div> 
    {% endblock  %}

webapp/writerpanel/templates/writers/edit-article.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Yayımlarım {% endblock %} 


{% block content %}

<form action="" method="POST">
  {% csrf_token %}
<div class="container mt-2 ">
    <h1>Makale Düzenle</h1>
    <div class="card">
      <div class="card-body">
        <div>
          <label class="required" for="id_baslik" >Başlık: </label>
          <input class="form-control d-flex flex-row" type="text" placeholder="" name="baslik" value="{{article.baslik}}">  
        </div>
        <p class="file-upload mt-2">
          Mevcut Yüklü Makale: 
          <a href="{% get_media_prefix %}{{article.makale}}">{{article.makale}}</a>
          <br>
          Mevcut Yerine Yüklenecek Makale:
          <input type="file" name="makale" id="id_makale">
        </p>
      </div>
    </div>
  </div>
  <div class="container mt-2 d-flex flex-row-reverse">
    <a type="button" class=" btn btn-danger" href="delete">Sil</a>
    <button type="submit" href="" name="submit" class="btnkayit btn btn-success me-2" value="submit" >Kaydet</button>
  </div>
</form>
  {% endblock  %}

webapp/writerpanel/templates/writers/edit-news.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Yayımlarım {% endblock %} 


{% block content %}
<form action="" enctype="multipart/form-data" method="post">
  {% csrf_token %}
<div class="container mt-2 ">
    <h1>Haber Düzenle</h1>
    <div class="card">
      <div class="card-body">
        <p class="file-upload">
         
          {% comment %} <a href="{% get_media_prefix %}{{post.resim}}">{{post.resim}}</a> {% endcomment %}
          <div class="container d-inline-flex">
            Güncel Resim: 
            <img src="{% get_media_prefix %}{{post.resim}}" class="ms-3"alt="Seismocode" width="50%" height="50%"> 
          </div>
          <br>
          <br>
          Yüklenecek Resim:
          <br>
          <input type="file" name="resim" accept="image/*" value="{{post.resim}}" id="id_resim">
          <br>
        </p>
        <div>
          <label class="required" for="id_baslik">Başlık:</label>
          <input class="form-control d-flex flex-row" type="text" placeholder="" name="baslik" id="baslik" value="{{post.baslik}}">  
          <br>
        </div>
          <h2 class="mt-2"></h2>
          İçerik:
          <br>
          {{form.media}}
          {{ icerik.value }}
          {{form.icerik}}
      </div>
    </div>
  </div>
  <div class="container mt-2 d-flex flex-row-reverse">
    <a type="button" class=" btn btn-danger" href="delete">Sil</a>
    <button type="submit" href="" name="submit" class="btnkayit btn btn-success me-2" value="submit" >Kaydet</button>
  </div> 
</form>
{% endblock  %}

webapp/writerpanel/templates/writers/my-writings.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Yayımlarım {% endblock %} 


{% block content %}
<div class="container mt-2 ">
    <h1>Haberlerim</h1>
    <div class="card">
      <div class="card-body">
        <div class="table-responsive-sm">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Başlık</th>
                <th scope="col">İçerik</th>
                <th scope="col">Yayınlanma Tarihi</th>
              </tr>
            </thead>
            <tbody>
              {% for post in  writers %}
              <tr>
                <td><a href="{% url 'edit_news' post.slug%}">{{post.baslik|striptags|title}}</a></td>
                <td>{{post.icerik|safe|truncatechars:20}}</td>
                <td>{{post.olusturulma_tarihi|date:"d/m/Y"}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="container mt-2 ">
    <h1>Makalelerim</h1>
    <div class="card">
      <div class="card-body">
        <div class="table-responsive-sm">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Başlık</th>
                <th scope="col">Dosya</th>
                <th scope="col">Yayınlanma Tarihi</th>
              </tr>
            </thead>
            <tbody>
              {% for article in  articles%}
              <tr>
                <td><a href="{% url 'edit_article' article.slug%}">{{article.baslik}}</a></td>
                <td><a href="{% get_media_prefix %}{{article.makale}}">{{article.makale}}</a></td>
                <td>{{article.olusturulma_tarihi|date:"d/m/Y"}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="container mt-2 d-flex flex-row-reverse">
    <a class="btnkayit btn btn-success " href="{% url 'add_news' %}" role="button">Haber Ekle</a>
    <a class="btnkayit btn btn-success me-2" href="{% url 'add_article' %}" role="button">Makale Ekle</a>
  </div>

{% endblock  %}
  